src/api/urls.py
from django.urls import path
from api.api import api_accept, api_vote, api_best_members, api_popular_tags

app_name = 'api'

urlpatterns = [
    path('vote/', api_vote, name='vote'),
    path('accept/', api_accept, name='accept'),
    path('best_members/', api_best_members, name='best_members'),
    path('popular_tags/', api_popular_tags, name='popular_tags')
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from question.views import HomeListView

from user.views import (
    RegisterView,
)

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('user/', include('user.urls', 'user')),

    path('admin/', admin.site.urls),
    path('api/', include('api.urls', 'api')),
    path('question/', include('question.urls', 'question')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/question/urls.py
from django.urls import path
from question.views import (
    CreateQuestionView,
    QuestionView,
)

app_name = 'question'

urlpatterns = [
    path('create/', CreateQuestionView.as_view(), name='create'),
    path('<slug:slug>/', QuestionView.as_view(), name='detail'),
]

src/user/urls.py
from django.urls import path
from user.views import (
    UserDetailView,
    UserUpdateView,
)

app_name = 'user'

urlpatterns = [
    path('<slug>/', UserDetailView.as_view(), name='detail'),
    path('<slug>/settings/', UserUpdateView.as_view(), name='settings'),
]

src/templates/snippets/footer.html
<div class="footer">
  <div class="text">
    <a href="#" target="_blank">xask</a> All rights reserved.
  </div>
</div>
</body>

</html>

src/templates/snippets/form.html
{% for field in form %}
{% csrf_token %}
<div class="field-wrapper">
  <div class="errors">
    {{ field.errors }}
  </div>
  <div class="field">
    {{ field }}
    <label for="{{ field.id_for_label }}"> {{ field.label }} </label>
  </div>
</div>
{% endfor %}

src/templates/snippets/header.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
  <title>xask</title>
</head>

<body>
  <div class="header">
    <div class="logo">
      <a href="{% url 'home' %}">xask</a>
    </div>

    <div class="list">
      <input type="search" name="search" id="search" placeholder="Search..." autocomplete="off">
      <a href="{% url 'question:create' %}" class="ask">Ask</a>
    </div>

    <div class="user">
      {% if user.is_authenticated %}

      {% if  user.photo %}
      <img class="profile-photo" src="{{ user.photo.url }}" alt="profile photo">
      {% else %}
      <img class="profile-photo" alt="profile photo">
      {% endif %}

      <div class="info">
        <a class="user" href="{% url 'user:detail' user.slug %}">{{ user.username }}</a>
        <div class="list">
          <a href="{% url 'user:settings' user.slug %}">Settings</a>
          <a href="{% url 'logout' %}?next={{ request.path }}">Log out</a>
        </div>
      </div>
      {% else %}
      <div class="info">
        <div class="list">
          <a href="{% url 'login' %}">Login</a>
          <a href="{% url 'register' %}">register</a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>

src/templates/snippets/left_sidebar.html
<div class="sidebar left"></div>

src/templates/snippets/pagination.html
<div class="pagination" id="pagination">
  <ul>
    {% if page_obj.has_previous %}
    <li><a href="?page=1">first</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
    {% endif %}

    <li class="current"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
    <li><a href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
    {% endif %}
  </ul>
</div>

src/templates/snippets/right_sidebar.html
<div class="sidebar right">
  <div class="tags" id="popular-tags">
    <p>Popular tags</p>
  </div>
  <div class="members" id="best-members">
    <p>Best members</p>
  </div>
</div>